import { Goleador } from './goleador';

export const goleador : Goleador [] = [
  {name: "Manu", lastName: "Garcia", pseudo: "M. Garcia", club: "Alaves", goles: 1},
  {name: "Munir", lastName: "El Haddadi", pseudo: "Munir", club: "Alaves", goles: 1},
  {name: "Alvaro", lastName: "Medran", pseudo: "Medran", club: "Alaves", goles: 1},
  {name: "Aritz", lastName : "Aduriz", pseudo: "Aduriz", club : "Athletic", goles: 4},
  {name: "Raul", lastName: "Garcia", pseudo: "Raul Garcia", club: "Athletic", goles: 2},
  {name: "Iker", lastName: "Muniain", pseudo: "Muniain", club: "Athletic", goles: 1},
  {name: "Iñaki", lastName: "Williams", pseudo: "Williams", club: "Athletic", goles: 2},
  {name: "Mikel", lastName: "Vesga", pseudo: "Vesga", club: "Athletic", goles: 1},
  {name: "Jose", lastName: "Gimenez", pseudo: "Gimenez", club: "Atletico", goles: 1},
  {name: "Angel", lastName : "Correa", pseudo: "Correa", club : "Atletico", goles: 3},
  {name: "", lastName : "Ferreira-Carrasco", pseudo : "Carrasco", club : "Atletico", goles: 3},
  {name: "Jesus", lastName: "Resurreccion", pseudo: "Koke", club: "Atletico", goles: 2},
  {name: "Thomas", lastName: "", pseudo: "Thomas", club: "Atletico", goles: 1},
  {name: "Antoine", lastName: "Griezmann", pseudo: "Griezmann", club: "Atletico", goles: 2},
  {name: "Saul", lastName: "Niguez", pseudo: "Saul", club: "Atletico", goles: 1},
  {name: "Lionel", lastName : "Messi", pseudo : "Messi", club : "Barcelona", goles: 11},
  {name: "Sergi", lastName: "Roberto", pseudo: "S. Roberto", club: "Barcelona", goles: 1},
  {name: "Gerard", lastName: "Pique", pseudo: "Pique", club: "Barcelona", goles: 1},
  {name: "Luis", lastName: "Suarez", pseudo: "Suarez", club: "Barcelona", goles: 3},
  {name: "Denis", lastName: "Suarez", pseudo: "D. Suarez", club: "Barcelona", goles: 2},
  {name: "", lastName: "", pseudo: "Paulinho", club: "Barcelona", goles: 2},
  {name: "Sergio", lastName: "Busquets", pseudo: "Busquets", club: "Barcelona", goles: 1},
  {name: "Sergio", lastName : "Leon", pseudo: "S. Leon", club : "Betis", goles: 4},
  {name: "", lastName : "Sanabria", pseudo : "Sanabria", club : "Betis", goles: 5},
  {name: "Joaquin", lastName : "", pseudo: "Joaquin", club : "Betis", goles: 3},
  {name: "", lastName: "Feddal", pseudo: "Feddal", club: "Betis", goles: 2},
  {name: "Joel", lastName: "Campbell", pseudo: "Campbell", club: "Betis", goles: 1},
  {name: "Fabian", lastName: "", pseudo: "Fabian", club: "Betis", goles: 1},
  {name: "Cristian", lastName: "Tello", pseudo: "Tello", club: "Betis", goles: 1},
  {name: "", lastName: "Sisto", pseudo: "Sisto", club: "Celta", goles: 2},
  {name: "Maxi", lastName : "Gomez", pseudo : "Maxi Gomez", club : "Celta", goles: 5},
  {name: "", lastName: "Cabral", pseudo: "Cabral", club: "Celta", goles: 1},
  {name: "", lastName: "Gomez", pseudo: "S. Gomez", club: "Celta", goles: 1},
  {name: "Pablo", lastName: "Hernandez", pseudo: "Hernandez", club: "Celta", goles: 1},
  {name: "Daniel", lastName: "Wass", pseudo: "Wass", club: "Celta", goles: 2},
  {name: "Fede", lastName: "Cartabia", pseudo: "Cartabia", club: "Deportivo", goles: 2},
  {name: "Sidnei", lastName: "", pseudo: "Sidnei", club: "Deportivo", goles: 1},
  {name: "Adrian", lastName: "Lopez", pseudo: "Adrian", club: "Deportivo", goles: 1},
  {name: "", lastName: "Andone", pseudo: "Andone", club: "Deportivo", goles: 2},
  {name: "Luisinho", lastName: "", pseudo: "Luisinho", club: "Deportivo", goles: 1},
  {name: "Celso", lastName: "Borges", pseudo: "Borges", club: "Deportivo", goles: 1},
  {name: "Lucas", lastName: "Perez", pseudo: "Lucas", club: "Deportivo", goles: 1},
  {name: "Charles", lastName: "", pseudo: "Charles", club: "Eibar", goles: 1},
  {name: "", lastName: "Galvez", pseudo: "Galvez", club: "Eibar", goles: 1},
  {name: "Sergi", lastName: "Enrich", pseudo: "Enrich", club: "Eibar", goles: 1},
  {name: "Leo", lastName: "Baptistao", pseudo: "Baptistao", club: "Espanyol", goles: 2},
  {name: "Gerard", lastName : "Moreno", pseudo : "Gerard", club : "Espanyol", goles: 3},
  {name: "Pablo", lastName: "Piatti", pseudo: "Piatti", club: "Espanyol", goles: 1},
  {name: "", lastName: "Arambarri", pseudo: "Arambarri", club: "Getafe", goles: 1},
  {name: "", lastName: "Jimenez", pseudo: "Jimenez", club: "Getafe", goles: 1},
  {name: "", lastName : "Rodriguez", pseudo : "Rodriguez", club : "Getafe", goles: 3},
  {name: "", lastName: "Shibasaki", pseudo: "Shibasaki", club: "Getafe", goles: 1},
  {name: "Jorge", lastName: "Molina", pseudo: "Molina", club: "Getafe", goles: 2},
  {name: "", lastName: "Bergara", pseudo: "Bergara", club: "Getafe", goles: 1},
  {name: "", lastName: "Amath", pseudo: "Amath", club: "Getafe", goles: 1},
  {name: "", lastName: "Alcala", pseudo: "Alcala", club: "Girona", goles: 1},
  {name: "Rodrigo", lastName : "Stuani", pseudo: "Stuani", club : "Girona", goles: 4},
  {name: "", lastName: "", pseudo: "Portu", club: "Girona", goles: 1},
  {name: "", lastName: "", pseudo: "Juanpe", club: "Girona", goles: 1},
  {name: "Jonathan", lastName: "Calleri", pseudo: "Calleri", club: "Las Palmas", goles: 2},
  {name: "Jonathan", lastName: "Viera", pseudo: "Viera", club: "Las Palmas", goles: 1},
  {name: "Loic", lastName: "Remy", pseudo: "Remy", club: "Las Palmas", goles: 2},
  {name: "Gabriel", lastName: "", pseudo: "Gabriel", club: "Leganes", goles: 2},
  {name: "", lastName: "Mantovani", pseudo: "Mantovani", club: "Leganes", goles: 1},
  {name: "", lastName: "Guerrero", pseudo: "Guerrero", club: "Leganes", goles: 1},
  {name: "", lastName: "Beauvue", pseudo: "Beauvue", club: "Leganes", goles: 1},
  {name: "", lastName: "", pseudo: "Eraso", club: "Leganes", goles: 1},
  {name: "", lastName: "Symanowski", pseudo: "Symanowski", club: "Leganes", goles: 1},
  {name: "", lastName: "Morales", pseudo: "Morales", club: "Levante", goles: 2},
  {name: "", lastName : "Bardhi", pseudo: "Bardhi", club : "Levante", goles: 3},
  {name: "Ivy", lastName: "Lopez", pseudo: "I. Lopez", club: "Levante", goles: 2},
  {name: "", lastName: "", pseudo: "Chema", club: "Levante", goles: 1},
  {name: "", lastName: "Gonzalez", pseudo: "D. Gonzalez", club: "Malaga", goles: 1},
  {name: "Diego", lastName: "Rolan", pseudo: "Rolan", club: "Malaga", goles: 2},
  {name: "", lastName: "Baysse", pseudo: "Baysse", club: "Malaga", goles: 1},
  {name: "Gareth", lastName: "Bale", pseudo: "Bale", club: "Real Madrid", goles: 2},
  {name: "Carlos", lastName: "Casemiro", pseudo: "Casemiro", club: "Real Madrid", goles: 1},
  {name: "Tony", lastName: "Kroos", pseudo: "Kroos", club: "Real Madrid", goles: 1},
  {name: "Marco", lastName: "Asensio", pseudo: "Asensio", club: "Real Madrid", goles: 2},
  {name: "Lucas", lastName: "Vasquez", pseudo: "Lucas", club: "Real Madrid", goles: 1},
  {name: "Borja", lastName: "Mayoral", pseudo: "Mayoral", club: "Real Madrid", goles: 1},
  {name: "Dani", lastName: "Ceballos", pseudo: "Ceballos", club: "Real Madrid", goles: 2},
  {name: "Francisco", lastName: "Alarcon", pseudo: "Isco", club: "Real Madrid", goles: 2},
  {name: "Karin", lastName: "Benzema", pseudo: "Benzema", club: "Real Madrid", goles: 1},
  {name: "Cristiano", lastName: "Ronaldo", pseudo: "Cristiano", club: "Real Madrid", goles: 1},
  {name: "Xabi", lastName: "Prieto", pseudo: "Prieto", club: "Real Sociedad", goles: 2},
  {name: "William", lastName : "José", pseudo: "William", club : "Real Sociedad",goles: 3},
  {name: "Juanmi", lastName : "", pseudo : "Juanmi", club : "Real Sociedad", goles: 3},
  {name: "Asier", lastName: "Ilarramendi", pseudo: "Ilarramendi", club: "Real Sociedad", goles: 2},
  {name: "Diego", lastName: "Llorente", pseudo: "Llorente", club: "Real Sociedad", goles: 2},
  {name: "Kevin", lastName: "", pseudo: "Kevin", club: "Real Sociedad", goles: 1},
  {name: "", lastName: "Elustondo", pseudo: "Elustondo", club: "Real Sociedad", goles: 2},
  {name: "Mikel", lastName : "Oryazabal", pseudo: "Oryazabal", club : "Real Sociedad",goles: 4},
  {name: "", lastName: "Lenglet", pseudo: "Lenglet", club: "Sevilla", goles: 1},
  {name: "", lastName: "Ganso", pseudo: "Ganso", club: "Sevilla", goles: 2},
  {name: "", lastName: "Ben Yedder", pseudo: "Ben Yedder", club: "Sevilla", goles: 1},
  {name: "", lastName: "", pseudo: "Nolito", club: "Sevilla", goles: 1},
  {name: "Luis", lastName: "Muriel", pseudo: "Muriel", club: "Sevilla", goles: 2},
  {name: "Jesus", lastName: "Navas", pseudo: "Navas", club: "Sevilla", goles: 1},
  {name: "Ever", lastName: "Banega", pseudo: "Banega", club: "Sevilla", goles: 1},
  {name: "Rodrigo", lastName : "", pseudo: "Rodrigo", club : "Valencia", goles: 5},
  {name: "Simone", lastName : "Zaza", pseudo : "Zaza", club : "Valencia", goles: 7},
  {name: "Santi", lastName: "Mina", pseudo: "Mina", club: "Valencia", goles: 2},
  {name: "", lastName: "Kondogbia", pseudo: "Kondogbia", club: "Valencia", goles: 2},
  {name: "Carlos", lastName: "Soler", pseudo: "Soler", club: "Valencia", goles: 1},
  {name: "Nacho", lastName: "Vidal", pseudo: "Vidal", club: "Valencia", goles: 1},
  {name: "Daniel", lastName: "Parejo", pseudo: "Parejo", club: "Valencia", goles: 1},
  {name: "", lastName: "Guedes", pseudo: "Guedes", club: "Valencia", goles: 1},
  {name: "Andreas", lastName: "Pereira", pseudo: "Pereira", club: "Valencia", goles: 1},
  {name: "Samu", lastName: "Castillejo", pseudo: "Castillejo", club: "Villarreal", goles: 1},
  {name: "Unai", lastName: "", pseudo: "Unai", club: "Villarreal", goles: 1},
  {name: "Carlos", lastName: "Bacca", pseudo: "Bacca", club: "Villarreal", goles: 2},
  {name: "Cedric", lastName : "Bakambu", pseudo : "Bakambu", club : "Villarreal", goles: 7}
];
